# Generated by Django 2.2 on 2020-07-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('overview', models.CharField(max_length=100, verbose_name='概説')),
                ('exptain', models.CharField(max_length=800, verbose_name='解説')),
                ('viewed_at', models.DateTimeField(blank=True, verbose_name='視聴日')),
                ('recorded_at', models.DateTimeField(blank=True, verbose_name='録画日')),
                ('genre', models.CharField(blank=True, max_length=50, verbose_name='ジャンル')),
            ],
        ),
    ]
