# Generated by Django 2.2 on 2020-07-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0001_initial'),
    ]

    operations = [

        migrations.RenameField(
            model_name='Movie',  # モデル名
            old_name='exptain',  # 変更前
            new_name='explain'  # 変更後
        )

    ]
