# Generated by Django 2.2 on 2020-07-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0002_auto_20200725_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='録画日'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='視聴日'),
        ),
    ]
